# Generated by Django 5.2.7 on 2025-10-30 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du modèle')),
                ('version', models.CharField(max_length=100, verbose_name='Version')),
                ('sensibilite', models.IntegerField(verbose_name='Sensibilité')),
                ('typesEpi', models.CharField(max_length=100, verbose_name="Types d'EPI détectés")),
                ('active', models.BooleanField(default=False, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle IA',
                'verbose_name_plural': 'Modèles IA',
                'db_table': 'modeles_ia',
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('surname', models.CharField(max_length=100, verbose_name='Prénom')),
                ('poste', models.CharField(max_length=100, verbose_name='Poste')),
                ('department', models.CharField(max_length=100, verbose_name='Département')),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('CONGE', 'En congé'), ('RETRAITE', 'Retraité')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'db_table': 'employes',
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeEpiManquants', models.CharField(max_length=500, verbose_name='EPI manquants')),
                ('image', models.ImageField(upload_to='alertes/%Y/%m/%d/', verbose_name='Image')),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('IGNORE', 'Ignoré')], default='NOUVEAU', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('niveau', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='MOYEN', max_length=20, verbose_name='Niveau de gravité')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='prepa_api_app.employe', verbose_name='Employé')),
                ('modeleIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='prepa_api_app.modeleia', verbose_name='Modèle IA')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'db_table': 'alertes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPPORT', 'Support Technique'), ('MAINTENANCE', 'Maintenance'), ('RESEAU', 'Réseau'), ('SECURITE', 'Sécurité')], max_length=50, verbose_name='Rôle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniciens', to='prepa_api_app.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Technicien',
                'verbose_name_plural': 'Techniciens',
                'db_table': 'techniciens',
                'ordering': ['employee__name'],
            },
        ),
    ]
